version: '3.8'

services:
  auth:
    image: ghcr.io/millbj92/sociium_auth:latest
    restart: unless-stopped
    container_name: auth
    ports:
      - '5002:5002'
    networks:
      - api
    environment:
      NODE_ENV: 'development'
      PORT: ${SRV_AUTH_PORT}
      JWT_ISSUER: ${SRV_AUTH_JWT_ISSUER}
      JWT_AUDIENCE: ${SRV_AUTH_JWT_AUDIENCE}
      OPENID_ISSUER: ${SRV_AUTH_OPENID_ISSUER}
      CERT_DIR: ${SRV_AUTH_CERT_DIR}
      OPENID_JWKS_URI: ${SRV_AUTH_OPENID_JWKS_URI}
      AUTH_KAFKA_BROKER_PORT: ${SRV_AUTH_KAFKA_BROKER_PORT}
      AUTH_KAFKA_BROKER_HOST: ${SRV_AUTH_KAFKA_BROKER_HOST}
      AUTH_KAFKA_SERVICE_NAME: ${SRV_AUTH_KAFKA_SERVICE_NAME}
      AUTH_KAFKA_CONSUMER_GROUP: ${SRV_AUTH_KAFKA_CONSUMER_GROUP}
      AUTH_KAFKA_CLIENT_ID: ${SRV_AUTH_KAFKA_CLIENT_ID}

networks:
  api:
    driver: bridge
