version: '3.8'

networks:
  api:
    driver: bridge

services:
  auth:
    container_name: auth
    build:
      context: ./
      cache_from:
        - node:16.14.0-alpine
      dockerfile: ./apps/services/auth/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: auth:dev
    ports:
      - '5002:5002'
    environment:
      NODE_ENV: 'development'
      PORT: '5002'
    networks:
      - api
    restart: on-failure
