# Default values for auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hosts:
  - sociium.io

auth:
  path: "/auth/"
  name: auth
  group: backend
  image:
    repository: ghcr.io/millbj92/sociium_auth
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
    containerPort: 5002
  service:
    type: ClusterIP
    port: 5002
  config:
    data:
      - key: key
        value: value


imagePullSecrets:
  - name: dockerconfigjson-github-com
