apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-env
  labels:
    group: {{ .Values.app.group }}
data:
{{- range .Values.app.config.data }}
   {{ .key }}: {{ .value | quote }}
{{- end }}
