apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    group: {{ .Values.app.group }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type:
    {{ .Values.app.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      name: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}-vs
spec:
  hosts: {{- range $i, $host := .Values.hosts }}
  - {{ $host }}
  {{- end }}
  gateways:
  - {{ .Values.environment.name }}-gateway
  http:
  - match:
    - uri:
        prefix: /{{.Values.app.name}}/
    rewrite:
        uri: /
    route:
    - destination:
        port:
          number: {{ .Values.app.service.port }}
        host: {{.Values.app.name}}-service
