apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.auth.name }}-env
  labels:
    group: {{ .Values.auth.group }}
data:
{{- range .Values.auth.config.data }}
   {{ .key }}: {{ .value | quote }}
{{- end }}
