apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}-service
  labels:
    group: {{ .Values.auth.group }}
spec:
  selector:
    app: {{ .Values.auth.name }}
  type:
    {{ .Values.auth.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.port }}
      name: http
